# Generated by Django 5.2.3 on 2025-06-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_url',
        ),
    ]
